### ISSUE TITLE
Incorrect login details were provided.

### ISSUE THREAD

**Issue by ProjectHelixCoin** [MSFTserver/TipBot#10]
I've set the exact same rpc details in the coin.conf as in the default.json but when i run the /bot/bot.js it keeps giving me the error that the login credentials are wrong so i dont think its that..

However, I'm missing a step in the readme where it tells us to edit the bot client id and secret token, where are we supposed to do this?

```
crazy@ubuntu:~/TipBot$ node ./bot/bot.js
[09-17-2018 03:02 am PST][TipBot] 11 aliases Loaded!
[09-17-2018 03:02 am PST][TipBot] unhandledRejection: Error: Incorrect login details were provided.
[09-17-2018 03:02 am PST][TipBot] uncaughtException: TypeError: Cannot read property 'send' of undefined
/home/crazy/TipBot/bot/bot.js:100
    .send('[' + time + ' PST][' + pm2Name + '] uncaughtException: ' + err);
    ^

TypeError: Cannot read property 'send' of undefined
    at process.on.err (/home/crazy/TipBot/bot/bot.js:100:5)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
```

![image](https://user-images.githubusercontent.com/42091981/45617143-b412c580-ba71-11e8-87a0-ca8a66eb08af.png)
![image](https://user-images.githubusercontent.com/42091981/45617208-db699280-ba71-11e8-9187-78fdd2f0c39b.png)

**Comment by MSFTserver** [comment]
that would be on thw discords website in the steps for setting up a bot there

**Comment by MSFTserver** [comment]
Create a bot and get the bots Token and Client ID: https://discordapp.com/developers/applications/me

After going to the link above click “new application”. Give it a name, picture, and description.

On the side bar navigation menu click "Bot" Click “Add Bot” and click “Yes, Do It!” when the dialog pops up.

Copy down the token used on this page to login and Client ID on the general info page to invite your new bot to your discord server.

**Comment by ProjectHelixCoin** [comment]
I made a bot, and its showing on discord as offline, but how do i link it to the code so it knows to use this bot

**Comment by ProjectHelixCoin** [comment]
Oh wow derp, i thought i had to pick the "coin token" there, haha

**Comment by MSFTserver** [comment]
lol
