### ISSUE TITLE
error ubuntu 16.05

### ISSUE THREAD

**Issue by FndNur1Labs** [MSFTserver/TipBot#21]
yarn start
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

all step follow

**Comment by MSFTserver** [comment]
this looks like an issue with yarn version, doesnt look like this error is stemming from any files in my project

**Comment by MSFTserver** [comment]
you could try updating your yarn version or trying with either `pm2 start` or just simply using node/npm

**Comment by MSFTserver** [comment]
Closing this issue for no responses, can reopen if still an issue
