### ISSUE TITLE
Error: Configuration property "moderation" is not defined

### ISSUE THREAD

**Issue by Tr0j4n9** [MSFTserver/TipBot#8]
Hello,
I am getting this error while running with pm2, yarn and `node bot/bot.js`
```/root/boxytipbot/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "moderation" is not defined
    at Config.get (/root/boxytipbot/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/root/boxytipbot/bot/bot.js:8:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9```


Thanks for your help!

**Comment by MSFTserver** [comment]
do you have this section in your config file?
```
"moderation":{
"pm2Name": "TipBot",
// Roles that have access to all commands.
"perms": ["Admin","Moderator","Community Leader","Bots"],
// Bot Devs!
"botDev": "Bot Developer",
// Channel to log the bots moderation..
"logchannel": "429853685179351050",
//channel that the tip message will reply in if Multi or Role tip is used.
"botspamchannels": ["429134627823812612", "429852470886268929"]
}
```

**Comment by Tr0j4n9** [comment]
Yes, I do

**Comment by MSFTserver** [comment]
if you did it wouldnt be telling you you didn't though

**Comment by ProjectHelixCoin** [comment]
I get the same error, while the moderation is there:
```
crazy@ubuntu:~/TipBot/bot$ node bot.js
WARNING: No configurations found in configuration directory:/home/crazy/TipBot/bot/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/crazy/TipBot/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "moderation" is not defined
    at Config.get (/home/crazy/TipBot/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/home/crazy/TipBot/bot/bot.js:8:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
![image](https://user-images.githubusercontent.com/42091981/45616245-246c1780-ba6f-11e8-8b56-0c824577fb21.png)

**Comment by ProjectHelixCoin** [comment]
https://github.com/MSFTserver/TipBot/pull/9

**Comment by MSFTserver** [comment]
that could also be the problem will merge #9 today

**Comment by crypto-king** [comment]
Whats is the log channel and botspamchannels? 
Are we suppose to change this? 
Where do these numbers come from?

**Comment by MSFTserver** [comment]
bot spam channel is the default channel where people can use the commands like deposit, log channel is used for bot logging basically everything printed to console also goes to that channel so you don't have to monitor it from the bots end,  to get the channels ID you have to turn on developer mode in settings of discord and either right click and select copy channel id or you can type `\#Channel-Name` and discord will instead print out its id like in the example below

![img](https://spee.ch/b/Screenshot20190103-214612.jpeg) 

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
